### ISSUE TITLE
学习了，谢谢大佬，这个.name是写在哪里的？

### ISSUE THREAD

**Issue by StephenWu5** [superman66/css-modules-demo#1]
![image](https://user-images.githubusercontent.com/32475322/57284023-f3fee980-70e2-11e9-9f1b-7f171784be04.png)

**Comment by StephenWu5** [comment]
:smile:

**Comment by superman66** [comment]
写在这里。https://github.com/superman66/css-modules-demo/blob/master/src/demo2/index.css
